In [2]:
import numpy as np


In [6]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [7]:
b=np.random.random((3,4))
print(b)

[[0.04989958 0.05219641 0.08866716 0.95792067]
 [0.55857692 0.98422453 0.58235978 0.66326928]
 [0.42871613 0.92222647 0.31684694 0.994447  ]]


In [9]:
c=np.ones((2,2))
print(c)
d=np.zeros((2,2))
print(d)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [13]:
e=np.random.random((6,3))
print(e)
tranpose=e.T
print(tranpose)

[[0.47477571 0.52861646 0.89381996]
 [0.44188667 0.52933861 0.48441551]
 [0.80537113 0.45746379 0.92651079]
 [0.72995924 0.38156371 0.04707525]
 [0.45100382 0.13826211 0.05389026]
 [0.41281282 0.27865953 0.76892009]]
[[0.47477571 0.44188667 0.80537113 0.72995924 0.45100382 0.41281282]
 [0.52861646 0.52933861 0.45746379 0.38156371 0.13826211 0.27865953]
 [0.89381996 0.48441551 0.92651079 0.04707525 0.05389026 0.76892009]]


In [22]:
f=np.random.random((2,3))
g=np.random.random((3,2))
h=np.dot(f,g)
print(f)
print(g)













print(h)

[[0.60645157 0.19261397 0.64620607]
 [0.16961597 0.66162912 0.3390118 ]]
[[0.64842833 0.50750343]
 [0.81643101 0.9792138 ]
 [0.89727151 0.67182107]]
[[1.13031869 0.93052136]
 [0.95434395 0.96171232]]
